language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - mv .env.behat.example .env
    - travis_retry composer self-update
    - travis_retry composer install --prefer-source --no-interaction
    - chmod -R 777 storage
    - php artisan test:run
    #- php artisan migrate --seed --no-interaction --env=testing --database=testing -vvv

script:
    - vendor/bin/phpspec run
    - vendor/bin/phpunit
    - vendor/bin/behat