language: php

php:
    - 5.5
    - 5.6
    - hhvm

before_script:
    - mv .env.behat.example .env
    - touch storage/database.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --prefer-source --no-interaction
    - chmod -R 777 storage
    - php artisan serve &
    - sleep 5 # give artisan serve some time to start
    - php artisan migrate --seed --no-interaction --env=testing -vvv

script:
    - vendor/bin/phpspec run
    - vendor/bin/phpunit
    - vendor/bin/behat